#! /bin/sh

#ERL_LIBS=`pwd`
#erl -make

case "$1" in
  start)
	
	echo "Starting SampleApp server" "erl_msgpack_sample"
	if erl -detached -s sample start -noshell -sname sampleapp@localhost; then
	    exit 0
	else
	    exit 1
	fi
	;;
  stop)
	echo "Stopping SampleApp server" "erl_msgpack_sample"
	if erl -eval 'rpc:call(sampleapp@localhost, sample, stop, []).' -s init stop -noshell -sname sampleapp_ctl@localhost ; then
	    exit 0
	else
	    exit 1
	fi
	;;

  *)
	echo "Usage: samplectl {start|stop}"
	exit 1
esac

exit 0
