name: Check All
run-name: triggered by ${{ github.actor }}
on: [push]
  #push:
  #  branches: [ $default-branch ]
  #pull_request:
  #  branches: [ $default-branch ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.3

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Test
      run: rebar3 as test eunit eqc
    - name: Check
      run: rebar3 xref dialyzer
